---
- include: basic.yml
- include: webtatic.yml

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
    disablerepo: epel

#- name: Clean all
#  shell: yum clean all

#- name: Makecache
#  shell: yum makecache